name: Daily Ruby.wasm Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-ruby-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release data
        id: get_release
        run: |
          set -x
          curl -LO https://github.com/ruby/ruby.wasm/releases/latest/download/ruby-head-wasm32-unknown-wasip1-full.tar.gz
          tar xfz ruby-head-wasm32-unknown-wasip1-full.tar.gz
          mv ruby-head-wasm32-unknown-wasip1-full/usr/local/bin/ruby.wasm dist/ruby.wasm

