name: Daily Ruby.wasm Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-ruby-wasm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "ruby-head-wasm32-unknown-wasip1-full"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release data
        env:
          VERSION: ${{ matrix.version }}
        id: get_release
        run: |
          set -x
          curl -LO https://github.com/ruby/ruby.wasm/releases/latest/download/${VERSION}.tar.gz
          ls
          tar xfz ${VERSION}.tar.gz
          ls -la ${VERSION}
          mkdir tmp
          mv ${VERSION}/usr/local/bin/ruby tmp/ruby.wasm
          ls tmp

      # - uses: ryand56/r2-upload-action@latest
      #   with:
      #     r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
      #     r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
      #     r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      #     r2-bucket: ${{ secrets.R2_BUCKET }}
      #     source-dir: tmp
      #     destination-dir: ./${{ matrix.version }}
